--Crear el TABLESPACE para el USUARIO
CREATE TABLESPACE DB_ECOMMERCE
DATAFILE 'C:\app\faust\product\18.0.0\oradata\XE\DB_ECOMMERCE.dbf'
SIZE 512M;

--Crear el TABLESPACE temporal para el USUARIO
CREATE TEMPORARY TABLESPACE DB_ECOMMERCE_TMP
TEMPFILE 'C:\app\faust\product\18.0.0\oradata\XE\DB_ECOMMERCE_TMP.dbf'
SIZE 512M;

--Alterar la sesión de Oracle para permitir crear roles y usuarios
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

--Crear el Rol Administrador
CREATE ROLE ADMINISTRADOR;

--Dar los permisos al Rol
GRANT ALTER ANY INDEX TO "ADMINISTRADOR";
GRANT ALTER ANY SEQUENCE TO "ADMINISTRADOR";
GRANT ALTER ANY TABLE TO "ADMINISTRADOR";
GRANT ALTER ANY TRIGGER TO "ADMINISTRADOR";
GRANT CREATE ANY INDEX TO "ADMINISTRADOR";
GRANT CREATE ANY SEQUENCE TO "ADMINISTRADOR";
GRANT CREATE ANY SYNONYM TO "ADMINISTRADOR";
GRANT CREATE ANY TABLE TO "ADMINISTRADOR";
GRANT CREATE ANY TRIGGER TO "ADMINISTRADOR";
GRANT CREATE ANY VIEW TO "ADMINISTRADOR";
GRANT CREATE PROCEDURE TO "ADMINISTRADOR";
GRANT CREATE PUBLIC SYNONYM TO "ADMINISTRADOR";
GRANT CREATE TRIGGER TO "ADMINISTRADOR";
GRANT CREATE VIEW TO "ADMINISTRADOR";
GRANT DELETE ANY TABLE TO "ADMINISTRADOR";
GRANT DROP ANY INDEX TO "ADMINISTRADOR";
GRANT DROP ANY SEQUENCE TO "ADMINISTRADOR";
GRANT DROP ANY TABLE TO "ADMINISTRADOR";
GRANT DROP ANY TRIGGER TO "ADMINISTRADOR";
GRANT DROP ANY VIEW TO "ADMINISTRADOR";
GRANT INSERT ANY TABLE TO "ADMINISTRADOR";
GRANT QUERY REWRITE TO "ADMINISTRADOR";
GRANT SELECT ANY TABLE TO "ADMINISTRADOR";
GRANT "CONNECT" TO "ADMINISTRADOR";
GRANT "RESOURCE" TO "ADMINISTRADOR";

--Crear el USUARIO
CREATE USER ADMIN_DB
IDENTIFIED BY "ecommerce"
DEFAULT TABLESPACE "DB_ECOMMERCE"
TEMPORARY TABLESPACE "DB_ECOMMERCE_TMP" ACCOUNT UNLOCK;

--Volcar el rol de ADMINISTRADOR a el usuario ADMIN_DB
GRANT ADMINISTRADOR TO ADMIN_DB;

--Dar acceso ilimitado a los TABLESPACE al usuario ADMIN_DB
GRANT UNLIMITED TABLESPACE TO "ADMIN_DB";
