-- Si la tabla ya fue agregada entonces aniadir el siguiente query
ALTER TABLE "ADMIN_DB"."USUARIO" ADD user_role varchar2(15);

--4.- INFO_PERSONAL
CREATE TABLE "ADMIN_DB"."INFO_PERSONAL" (
 ID_INFO_USER NUMBER(6) NOT NULL,
 ID_USUARIO NUMBER(6) NOT NULL,
 APELLIDO VARCHAR2(15) NOT NULL,
 NOMBRE VARCHAR2(15) NOT NULL,
 CEDULA VARCHAR2(15),
 CORREO VARCHAR2(76),
 NO_TELEFONO NUMBER(25),
 FECHA_NACIMIENTO DATE,
 EDAD NUMBER(3),
 CONSTRAINT INFO_PERSONAL_PK PRIMARY KEY 
 (
 	ID_INFO_USER
 )
 ENABLE
) TABLESPACE "DB_ECOMMERCE";

--5.- DIRECCIÓN
CREATE TABLE "ADMIN_DB"."DIRECCION" (
 ID_USUARIO NUMBER(6) NOT NULL,
 CIUDAD VARCHAR2(15),
 ID_DIRECCION NUMBER(6) NOT NULL,
 N_CASA NUMBER(4),
 REGION VARCHAR2(40),
 CALLE NUMBER(5),
 DIRECCION_EXACTA VARCHAR2(80),
 PAIS VARCHAR2(20),
 CONSTRAINT DIRECCION_PK PRIMARY KEY 
 (
 	ID_DIRECCION
 )
 ENABLE
) TABLESPACE "DB_ECOMMERCE";

--** CREANDO TABLA ENVIO **
CREATE TABLE "ADMIN_DB"."ENVIO" (
  ID_ENVIO NUMBER(6) NOT NULL,
  ID_DIRECCION NUMBER(6) NOT NULL,
  ID_ORDEN NUMBER(6) NOT NULL,
  ID_METODOTRANSPORTE NUMBER(6) NOT NULL,
  CONSTRAINT ENVIO_PK PRIMARY KEY 
  (
  	ID_ENVIO
  )
  ENABLE
) TABLESPACE "DB_ECOMMERCE";

--** CREANDO TABLA FACTURA **
CREATE TABLE "ADMIN_DB"."FACTURA" (
  ID_FACTURA NUMBER(6) NOT NULL,
  ID_ORDEN NUMBER(6) NOT NULL,
  SALDOTOTAL NUMBER(5,2) NOT NULL,
  ID_ESTADOFACTURA VARCHAR2(15) NOT NULL,
  ID_MONEDA NUMBER(4) NOT NULL,
  CONSTRAINT FACTURA_PK PRIMARY KEY
  (
  	ID_FACTURA
  )
  ENABLE
) TABLESPACE "DB_ECOMMERCE";

--- CREANDO TABLA MONEDA ***
CREATE TABLE "ADMIN_DB"."MONEDA" (
	ID_MONEDA NUMBER(4) NOT NULL,
	TIPO_MONEDA VARCHAR2(12) NOT NULL,
	VALOR NUMBER(5,2) NOT NULL,
	ID_IMPUESTO NUMBER(4,2) NOT NULL,
	CONSTRAINT MONEDA_PK PRIMARY KEY 
	(
		ID_MONEDA
	)
	ENABLE
	) TABLESPACE "DB_ECOMMERCE";

-- CREANDO TABLA ESTADO_FACTURA **
CREATE TABLE "ADMIN_DB"."ESTADO_FACTURA" (
ID_ESTADOFACTURA NUMBER(5) NOT NULL,
DESCRIPCION VARCHAR2(20) NOT NULL,
CONSTRAINT ESTADO_FACTURA_PK PRIMARY KEY 
(
	ID_ESTADOFACTURA
)
ENABLE
) TABLESPACE "DB_ECOMMERCE";
 
-- CREANDO TABLA IMPUESTO **
CREATE TABLE "ADMIN_DB"."IMPUESTO"
(
ID_IMPUESTO NUMBER(4) NOT NULL,
DESCRIPCION VARCHAR2(20) NOT NULL,
ESTADO_IMPUESTO VARCHAR(15) NOT NULL,
CONSTRAINT IMPUESTO_PK PRIMARY KEY 
(
	ID_IMPUESTO
)
ENABLE
) TABLESPACE "DB_ECOMMERCE";

--** CREANDO TABLA METODO_TRANSPORTE **
CREATE TABLE "ADMIN_DB"."METODO_TRANSPORTE" (
  ID_METODOTRANSPORTE NUMBER(6) NOT NULL,
  ID_DETALLES_METTRANSPORTE NUMBER(6) NOT NULL,
  NOMBRE_CONDUCTOR VARCHAR2(20) NOT NULL,
  NOMBRE_AYUDANTE VARCHAR2(20) NOT NULL,
  CONSTRAINT METODO_TRANSPORTE_PK PRIMARY KEY 
  (
  	ID_METODOTRANSPORTE
  )
  ENABLE
) TABLESPACE "DB_ECOMMERCE";

-- CREANDO TABLA DETALLES_METTRANSPORTE **
CREATE TABLE "ADMIN_DB"."DETALLES_METTRANSPORTE" (
ID_DETALLES_METTRANSPORTE NUMBER(5) NOT NULL,
ID_TIPO_MET_TRANSPORTE VARCHAR2(15) NOT NULL,
ID_CONTENIDO VARCHAR2(20) NOT NULL,
CONSTRAINT DETALLES_METTRANSPORTE_PK PRIMARY KEY 
(
	ID_DETALLES_METTRANSPORTE
)
  ENABLE
) TABLESPACE "DB_ECOMMERCE";

-- CREANDO TABLA TIPO_MET_TRANSPORTE**
CREATE TABLE "ADMIN_DB"."TIPO_MET_TRANSPORTE" (
ID_TIPO_METTRANSPORTE NUMBER(5) NOT NULL,
DESCRIPCION VARCHAR(20) NOT NULL,
CONSTRAINT TIPO_MET_TRANSPORTE_PK PRIMARY KEY 
(
	ID_TIPO_METTRANSPORTE
)
  ENABLE
) TABLESPACE "DB_ECOMMERCE";

-- CREANDO TABLA CONTENIDO**
CREATE TABLE "ADMIN_DB"."CONTENIDO" (
ID_CONTENIDO NUMBER(5) NOT NULL,
DESCRIPCION VARCHAR2(20) NOT NULL,
TIPO_CONTENIDO VARCHAR2(15) NOT NULL,
ID_FRAGILIDAD NUMBER(5) NOT NULL,
CONSTRAINT CONTENIDO_PK PRIMARY KEY 
(
	ID_CONTENIDO
)
  ENABLE
) TABLESPACE "DB_ECOMMERCE";

-- CREANDO TABLA FRAGILIDAD**
CREATE TABLE "ADMIN_DB"."FRAGILIDAD" (
ID_FRAGILIDAD NUMBER(5) NOT NULL,
DESCRIPCION VARCHAR2(20) NOT NULL,
ID_INSTRUCTIVO VARCHAR(30) NOT NULL,
CONSTRAINT FRAGILIDAD_PK PRIMARY KEY 
(
	ID_FRAGILIDAD
)
  ENABLE
) TABLESPACE "DB_ECOMMERCE";

-- CREANDO TABLA INSTRUCTIVO**
CREATE TABLE "ADMIN_DB"."INSTRUCTIVO" (
ID_INSTRUCTIVO NUMBER(5) NOT NULL,
DESCRIPCION VARCHAR(20) NOT NULL,
CONSTRAINT INSTRUCTIVO_PK PRIMARY KEY 
(
	ID_INSTRUCTIVO
)
  ENABLE
) TABLESPACE "DB_ECOMMERCE";

--** CREANDO TABLA METODO DE PAGO **
CREATE TABLE "ADMIN_DB"."METODO_PAGO" (
  ID_METOD_PAGO NUMBER(6) NOT NULL,
  NOMBRE VARCHAR2(20) NOT NULL,
  TIPO_MONEDA VARCHAR2(10) NOT NULL,
  CONSTRAINT METODO_PAGO_PK PRIMARY KEY 
  (
  	ID_METOD_PAGO
  )
  ENABLE
) TABLESPACE "DB_ECOMMERCE";

--** CREANDO TABLA ORDEN **
CREATE TABLE "ADMIN_DB"."ORDEN" (
  ID_ORDEN NUMBER(6) NOT NULL,
  ID_DETALLE_ORDEN NUMBER(6) NOT NULL,
  ID_CLIENTE NUMBER(6) NOT NULL,
  CONSTRAINT ORDEN_PK PRIMARY KEY 
  (
  	ID_ORDEN
  )
  ENABLE
) TABLESPACE "DB_ECOMMERCE";

--CREANDO LA TABLA PRODUCTO.
CREATE TABLE "ADMIN_DB"."PRODUCTO" (
	ID_PRODUCTO NUMBER(6) NOT NULL,
	DESCRIPCION VARCHAR2(20),
	ID_TIPO_PROD NUMBER(6) NOT NULL,
	PRECIO_UNITARIO NUMBER(6,2) NOT NULL,
	CONSTRAINT PRODUCTO_PK PRIMARY KEY 
	(
		ID_PRODUCTO
	)
	ENABLE
) TABLESPACE "DB_ECOMMERCE" ;

--CREANDO LA TABLA TIPO_PRODUCTO.
CREATE TABLE "ADMIN_DB"."TIPO_PRODUCTO" (
	ID_TIPO_PROD NUMBER(6) NOT NULL,
	DESCRIPCION VARCHAR2(30),
	CONSTRAINT TIPO_PRODUCTO_PK PRIMARY KEY 
	(
		ID_TIPO_PROD
	)
	ENABLE
) TABLESPACE "DB_ECOMMERCE" ;

--CREANDO LA TABLA DETALLE_ORDEN.
CREATE TABLE "ADMIN_DB"."DETALLE_ORDEN" (
	ID_DETALLE_ORDEN NUMBER(6) NOT NULL,
	ID_ORDEN NUMBER(6) NOT NULL,
	DESCRIPCION VARCHAR2(20),
	ID_CARRITO NUMBER(6) NOT NULL,
	CONSTRAINT DETALLE_ORDEN_PK PRIMARY KEY 
	(
		ID_DETALLE_ORDEN
	)
	ENABLE
) TABLESPACE "DB_ECOMMERCE" ;

--CREANDO LA TABLA CARRITO.
CREATE TABLE "ADMIN_DB"."CARRITO" (
    ID_CARRITO NUMBER(6) NOT NULL,
    ID_PRODUCTO NUMBER(6) NOT NULL,
	CANTIDAD_PRODUCTO NUMBER(6) NOT NULL,
  	PRECIO_UNITARIO NUMBER(6,2) NOT NULL,
    PRECIO_NETO NUMBER(6,2) NOT NULL,
    CONSTRAINT CARRITO_PK PRIMARY KEY 
    (
    	ID_CARRITO
    )
	ENABLE
) TABLESPACE "DB_ECOMMERCE" ;

--CREANDO LA TABLA INVENTARIO.
CREATE TABLE "ADMIN_DB"."INVENTARIO" (
	ID_INVENTARIO NUMBER(6) NOT NULL,
	DESCRIPCION VARCHAR2(20),
	ID_PRODUCTO NUMBER(6) NOT NULL,
	CANTIDAD NUMBER(10),
	ID_DIRECCION NUMBER(6) NOT NULL,
	ID_PROVEEDOR NUMBER(6) NOT NULL,
	CONSTRAINT INVENTARIO_PK PRIMARY KEY 
	(
		ID_INVENTARIO
	)
	ENABLE
) TABLESPACE "DB_ECOMMERCE" ;

--CREANDO LA TABLA PROVEEDOR.
CREATE TABLE "ADMIN_DB"."PROVEEDOR" (
	ID_PROVEEDOR NUMBER(6) NOT NULL,
	DESCRIPCION VARCHAR2(20),
	ID_TIPO_PROV NUMBER(6) NOT NULL,
	ID_METODOTRANSPORTE NUMBER(6) NOT NULL,
	ID_DIRECCION NUMBER(6) NOT NULL,
	CONSTRAINT PROVEEDOR_PK PRIMARY KEY 
	(
		ID_PROVEEDOR
	)
	ENABLE
) TABLESPACE "DB_ECOMMERCE" ;

--CREANDO LA TABLA TIPO_PROVEEDOR.
CREATE TABLE "ADMIN_DB"."TIPO_PROVEEDOR" (
	ID_TIPO_PROV NUMBER(6) NOT NULL,
  DESCRIPCION VARCHAR2(80),
  CONSTRAINT TIPO_PROVEEDOR_PK PRIMARY KEY 
  (
  	ID_TIPO_PROV
  )
  ENABLE
) TABLESPACE "DB_ECOMMERCE";



--AQUÍ IRÁN TODOS LOS ALTER'S.----------------------------------------------------------------------------------------------------
--ALTERACIÓN DE LA PRIMERA TABLA.
-- ALTER TABLE "ADMIN_DB"."CLIENTE"
-- ADD CONSTRAINT CLIENT_TC_FK
-- FOREIGN KEY (ID_TIPOCLIENTE)
-- REFERENCES TIPO_CLIENTE (ID_TIPOCLIENTE)
-- ENABLE;

-- ALTER TABLE "ADMIN_DB"."CLIENTE"
-- ADD CONSTRAINT CLIENT_TC_FK2
-- FOREIGN KEY (ID_USUARIO)
-- REFERENCES USUARIO (ID_USUARIO)
-- ENABLE;

-- --ALTERACIÓN DE LA TABLA TIPO_CLIENTE.
-- ALTER TABLE "ADMIN_DB"."TIPO_CLIENTE"
-- ADD CONSTRAINT TC_CLIENT_FK
-- FOREIGN KEY (ID_CLIENTE)
-- REFERENCES CLIENTE (ID_CLIENTE)
-- ENABLE;

-- --ALTERACIÓN DE LA TABLA ENVIO.
-- ALTER TABLE "ADMIN_DB"."ENVIO"
-- ADD CONSTRAINT ENVIO_FK
-- FOREIGN KEY (ID_ORDEN)
-- REFERENCES ORDEN (ID_ORDEN)
-- ENABLE;

-- ALTER TABLE "ADMIN_DB"."ENVIO"
-- ADD CONSTRAINT ENVIO_FK2
-- FOREIGN KEY (ID_METODOTRANSPORTE)
-- REFERENCES METODO_TRANSPORTE (ID_METODOTRANSPORTE)
-- ENABLE;

-- --ALTERACIÓN DE LA TABLA FACTURA.
-- ALTER TABLE "ADMIN_DB"."FACTURA"
-- ADD CONSTRAINT FACTURA_FK
-- FOREIGN KEY (ID_ORDEN)
-- REFERENCES ORDEN (ID_ORDEN)
-- ENABLE;

-- ALTER TABLE "ADMIN_DB"."FACTURA"
-- ADD CONSTRAINT FACTURA_FK2
-- FOREIGN KEY (ID_METOD_PAGO)
-- REFERENCES METODO_PAGO (ID_METOD_PAGO)
-- ENABLE;

-- --ALTER DE LA TABLA PRODUCTO.
-- ALTER TABLE "ADMIN_DB"."PRODUCTO"
-- ADD CONSTRAINT PRODUCTO_FK
-- FOREIGN KEY (ID_TIPO_PROD)
-- REFERENCES TIPO_PRODUCTO (ID_TIPO_PROD)
-- ENABLE;

-- --ALTER DE LA TABLA DETALLE_ORDEN.
-- ALTER TABLE "ADMIN_DB"."CARRTIO"
-- ADD CONSTRAINT DETALLE_ORDEN_FK
-- FOREIGN KEY (ID_CARRITO)
-- REFERENCES CARRITO (ID_CARRITO)
-- ENABLE;

-- ALTER TABLE "ADMIN_DB"."DETALLE_ORDEN"
-- ADD CONSTRAINT DETALLE_ORDEN_FK2
-- FOREIGN KEY (ID_ORDEN)
-- REFERENCES ORDEN (ID_ORDEN)
-- ENABLE;

-- --ALTER DE LA TABLA CARRITO.
-- ALTER TABLE "ADMIN_DB"."DETALLE_ORDEN"
-- ADD CONSTRAINT CARRITO_FK
-- FOREIGN KEY (ID_PRODUCTO)
-- REFERENCES PRODUCTO (ID_PRODUCTO);
-- ENABLE;

-- --ALTER DE LA TABLA INVENTARIO.
-- ALTER TABLE "ADMIN_DB"."INVENTARIO"
-- ADD CONSTRAINT INVENTARIO_FK
-- FOREIGN KEY (ID_PRODUCTO)
-- REFERENCES PRODUCTO (ID_PRODUCTO)
-- ENABLE;

-- ALTER TABLE "ADMIN_DB"."INVENTARIO"
-- ADD CONSTRAINT INVENTARIO_FK2
-- FOREIGN KEY (ID_PROVEEDOR)
-- REFERENCES PROVEEDOR(ID_PROVEEDOR)
-- ENABLE;

-- ALTER TABLE "ADMIN_DB"."INVENTARIO"
-- ADD CONSTRAINT INVENTARIO_FK3
-- FOREIGN KEY (ID_DIRECCION)
-- REFERENCES DIRECCION (ID_DIRECCION)
-- ENABLE;

-- --ALTER DE LA TABLA PROVEEDOR.
-- ALTER TABLE "ADMIN_DB"."PROVEEDOR"
-- ADD CONSTRAINT PROVEEDOR_FK
-- FOREIGN KEY (ID_TIPO_PROV)
-- REFERENCES TIPO_PROVEEDOR (ID_TIPO_PROV)
-- ENABLE;

-- ALTER TABLE "ADMIN_DB"."PROVEEDOR"
-- ADD CONSTRAINT PROVEEDOR_FK2
-- FOREIGN KEY (ID_METODOTRANSPORTE)
-- REFERENCES METODO_TRANSPORTE (ID_METODOTRANSPORTE)
-- ENABLE;

-- ALTER TABLE "ADMIN_DB"."PROVEEDOR"
-- ADD CONSTRAINT PROVEEDOR_FK3
-- FOREIGN KEY (ID_DIRECCION)
-- REFERENCES DIRECCION (ID_DIRECCION)
-- ENABLE;

-- ALTER TABLE "ADMIN_DB"."INFO_PERSONAL"
-- ADD CONSTRAINT INFO_PERSONAL_FK
-- FOREIGN KEY (ID_USUARIO)
-- REFERENCES USUARIO (ID_USUARIO)
-- ENABLE;

-- ALTER TABLE "ADMIN_DB"."DIRECCION"
-- ADD CONSTRAINT DIRECC_USUARIO_FK
-- FOREIGN KEY (ID_USUARIO)
-- REFERENCES USUARIO (ID_USUARIO)
-- ENABLE;

-- ALTER TABLE "ADMIN_DB"."ENVIO"
-- ADD CONSTRAINT ENVIO_FK
-- FOREIGN KEY (ID_DIRECCION)
-- REFERENCES DIRECCION (ID_DIRECCION)
-- ENABLE;
